apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpressdb
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: dbname
        volumeMounts:
        - name: webstorage
          mountPath: /var/www/html
      volumes:
        - name: webstorage
          persistentVolumeClaim:
            claimName: webstorage
