kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quobyte-csi-test-silver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: quobyte-silver
