---
- hosts: trendingserver 
  any_errors_fatal: false
  vars_files:
    - vars/trendingserver-vars.yaml 
  become: yes
  tasks:
    - name: Install Prometheus packages Debian-Flavor 
      apt:
        name: prometheus 
        state: present
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Copy Prometheus config
      template:
         src: templates/prometheus.jinja2
         dest: /etc/prometheus/prometheus.yml
         mode: '0644'

    - name: Restart Prometheus 
      service:
        name: prometheus
        state: restarted
        enabled: yes

    - name: Add Grafana repository signing key
      apt_key:
        url: https://packages.grafana.com/gpg.key 
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Add grafana apt repository to sources list
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install Grafana package Debian-Flavor 
      apt:
        name: grafana
        state: present
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Write out Grafana Prometheus datasource 
      template:
        src: templates/grafana_prometheus_source.yaml
        dest: "/etc/grafana/provisioning/datasources/prometheus.yaml"

    - name: Enable Grafana services
      service:
        enabled: yes
        state: started
        name: grafana-server

# todo: import quobyte dashboard
